"""
Collapse Model core metrics module

Modules:
    reff                — r_eff effective rank computation and Collapse Model prediction formulas
    subspace_alignment  — SA_k subspace alignment (V channel alpha)
    grassmann           — Grassmann manifold geometry tools (principal angles, geodesic distance)
    direction_gain      — Δ_dir direction gain criterion and greedy dataset selection
    target_conditioned  — target A-optimal design, D-optimal baseline, and PSD sketches
"""
from .subspace_alignment import compute_subspace_alignment, compute_multiscale_sa
from .collapse_core import (
    collapse_4s,
    collapse_4s_predict,
    effective_rank,
    effective_rank_from_scatter,
    effective_rank_from_singular_values,
    energy_dominant_ranks,
    is_superadditive,
    nuclear_mass,
    superadditivity_delta,
)
from .reff import predict_reff_collapse, reff_bounds, reff_theoretical_prediction
from .grassmann import grassmann_distance, principal_angles, GrassmannLoss
from .direction_gain import direction_gain
from .target_conditioned import (
    AdaptiveSketchResult,
    AdaptiveSketchStep,
    PSDEigendecomposition,
    PSDLowRankSketch,
    RidgeStatistics,
    RiskInterval,
    SelectionResult,
    SelectionStep,
    adaptive_sketch_target_a,
    aggregate_gram,
    block_marginal_gain,
    candidate_sketch_intervals,
    certified_minimum,
    combine_ridge_statistics,
    continuous_target_a,
    decompose_psd,
    d_opt_information_gain,
    exhaustive_target_a,
    gram_from_features,
    greedy_d_optimal,
    greedy_target_a,
    make_feature_sketch,
    make_psd_sketch,
    posterior_covariance,
    ridge_solution,
    ridge_squared_risk,
    ridge_statistics,
    sample_marginal_gain,
    second_moment,
    sketch_from_decomposition,
    sketch_target_a_interval,
    target_a_objective,
    target_a_risk,
)

__all__ = [
    "AdaptiveSketchResult",
    "AdaptiveSketchStep",
    "GrassmannLoss",
    "PSDEigendecomposition",
    "PSDLowRankSketch",
    "RidgeStatistics",
    "RiskInterval",
    "SelectionResult",
    "SelectionStep",
    "adaptive_sketch_target_a",
    "aggregate_gram",
    "block_marginal_gain",
    "candidate_sketch_intervals",
    "certified_minimum",
    "collapse_4s",
    "collapse_4s_predict",
    "combine_ridge_statistics",
    "compute_multiscale_sa",
    "compute_subspace_alignment",
    "continuous_target_a",
    "decompose_psd",
    "d_opt_information_gain",
    "direction_gain",
    "effective_rank",
    "effective_rank_from_scatter",
    "effective_rank_from_singular_values",
    "energy_dominant_ranks",
    "exhaustive_target_a",
    "gram_from_features",
    "grassmann_distance",
    "greedy_d_optimal",
    "greedy_target_a",
    "is_superadditive",
    "make_feature_sketch",
    "make_psd_sketch",
    "nuclear_mass",
    "posterior_covariance",
    "predict_reff_collapse",
    "principal_angles",
    "reff_bounds",
    "reff_theoretical_prediction",
    "ridge_solution",
    "ridge_squared_risk",
    "ridge_statistics",
    "sample_marginal_gain",
    "second_moment",
    "sketch_from_decomposition",
    "sketch_target_a_interval",
    "superadditivity_delta",
    "target_a_objective",
    "target_a_risk",
]
